---
title: "project3rmd"
author: "Aroon Prabhu"
date: "3/25/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Cleaning 

```{r}

shotlog <- read.csv("shot_logs.csv")

shotlog$FGM <- NULL
shotlog$PERIOD <- as.factor(shotlog$PERIOD)
shotlog$PTS_TYPE <- as.factor(shotlog$PTS_TYPE)
shotlog$CLOSEST_DEFENDER <- NULL
shotlog$CLOSEST_DEFENDER_PLAYER_ID <- NULL
shotlog$PTS <- NULL
shotlog$FGM <- NULL
shotlog$GAME_ID <- NULL
shotlog$MATCHUP <- NULL
shotlog$W <- NULL
shotlog$FINAL_MARGIN <- NULL
shotlog$player_id <- NULL
shotlog$SHOT_CLOCK[is.na(shotlog$SHOT_CLOCK)] <- 0
shotlog <- na.omit(shotlog)
shotlog$GAME_CLOCK <- as.numeric(shotlog$GAME_CLOCK)
shotlog$GAME_CLOCK <- NULL
str(shotlog)



```

## Russell Westbrook Shot Making Models
```{r}
russellwestbrook <- shotlog[shotlog$player_name == "russell westbrook", ]
russellwestbrook$player_name <- NULL
str(russellwestbrook)
logisticwestbrook <-glm(russellwestbrook$SHOT_RESULT ~ ., data = russellwestbrook, family = "binomial")
summary(logisticwestbrook)
```